package exceptionhandling;

import java.util.Scanner;

public class ExceptionHandling {
      
    public static void main(String[] args)
     
    {
        int a=10, b=0, c;
        
        Scanner sc=new Scanner(System.in);
        
        System.out.println("Enter 2 num");
        a=sc.nextInt();
        b=sc.nextInt();
        
        try
        {  
        c=a/b;
        System.out.println("Division is"+c);
        }
        catch(ArithmeticException e)
        {
            System.out.println("Denominator should not be 0");
        }
        System.out.println("Bye");
    }
    
}
